### ISSUE TITLE
Fifty and TwoHundred day ChangePercent values incorrect

### ISSUE THREAD

**Issue by gwilford** [iprak/yahoofinance#74]
They need to be multiplied by 100 . E.g. example percentage attribute below should be -11

TwoHundredDayAverage                           22,769.63
TwoHundredDayAverageChange                -2,511.97
TwoHundredDayAverageChangePercent          -0.11

**Comment by iprak** [comment]
I agree. All percentage values should be multiplied by 100 so that they can be directly displayed. However, any other calculation being done using them would need similar adjustment.

- regularMarketChangePercent
- fiftyDayAverageChangePercent
- preMarketChangePercent
- postMarketChangePercent
- twoHundredDayAverageChangePercent
