### ISSUE TITLE
Url to stock chart

### ISSUE THREAD

**Issue by Tom-ahawk** [iprak/yahoofinance#84]
Using your integration for quick look at my main stocks. 
Would be nice to have a stock attribute in the form as an url to Yahoo charts for the stock.

**Comment by iprak** [comment]
I feel this is a very specific use case. The chart url for a symebol is just https://finance.yahoo.com/chart/symbol. How are you planning to use the url?

**Comment by Tom-ahawk** [comment]
Using the

**Comment by iprak** [comment]
That is a neat card.

I don't know how clickable links can be generate by it but it is through advanced formatting the prefix can be used to generate the url data. - https://github.com/custom-cards/flex-table-card/blob/master/docs/example-cfg-simple-cell-formatting.md

This proposed data attribute feels redundant to me and would like to avoid it since the symbol values can be tracked for longer periods.

**Comment by Tom-ahawk** [comment]
Got it working like this:
```
  - name: Link
    data: symbol
    modify: '''<a href=https://finance.yahoo.com/quote/'' + x + ''>Y</a>'''
```
